### ISSUE TITLE
Saxon-HE-9.8.0-2.jar not found. Saxon-HE-10.6.jar is ok !

### ISSUE THREAD

**Issue by ghost** [OpenMath/OMSTD#71]
Please note that, trivially, the file install-jars is not up-to-date.
New file is, for me: wget https://search.maven.org/remotecontent?filepath=net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar
after this copy/rename: 

cp Saxon-HE-10.6.jar /tmp/jars/saxon9he.jar

it's ok for me.
Roland

**Comment by JamesHDavenport** [comment]
Thanks for this bug report.  I don't have access rights to make this fix - @Michael ***@***.***>: can you?

James Davenport
Hebron & Medlock Professor of Information Technology, University of Bath
National Teaching Fellow 2014;  DSc (honoris causa) UVT
Former Fulbright CyberSecurity Scholar (at New York University)
Former Vice-President and Academy Chair, British Computer Society


My workload obliges me to work, and send e-mails, outside working hours, but I don’t expect recipients to respond outside their working hours

________________________________
From: Roland Coghetto ***@***.***>
Sent: 11 December 2021 09:38
To: OpenMath/OMSTD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenMath/OMSTD] Saxon-HE-9.8.0-2.jar not found. Saxon-HE-10.6.jar is ok ! (Issue #71)


CAUTION:  This email came from outside of the University. To keep your account safe, only click on links and open attachments if you know the person who sent the email, or you expected to receive this communication.



Please note that, trivially, the file install-jars is not up-to-date.
New file is, for me: wget https://search.maven.org/remotecontent?filepath=net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsearch.maven.org%2Fremotecontent%3Ffilepath%3Dnet%2Fsf%2Fsaxon%2FSaxon-HE%2F10.6%2FSaxon-HE-10.6.jar&data=04%7C01%7Cmasjhd%40bath.ac.uk%7Cd9d288b4e6d444cc6e5e08d9bc8a076b%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637748123273833451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9yIxwAD5ORbVVRicdj2pJ0XqtpbM01CLbCLcVv3nbJg%3D&reserved=0>
after this copy/rename:

cp Saxon-HE-10.6.jar /tmp/jars/saxon9he.jar

it'ok for me.
Roland

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenMath%2FOMSTD%2Fissues%2F71&data=04%7C01%7Cmasjhd%40bath.ac.uk%7Cd9d288b4e6d444cc6e5e08d9bc8a076b%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637748123273843401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l4gFzMkCinkcsp6pesdvpqC3MypHEiBPzq6ydBE2EzU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABV5VGPMEBY644XIOB2ZDJ3UQML2LANCNFSM5J22B3LA&data=04%7C01%7Cmasjhd%40bath.ac.uk%7Cd9d288b4e6d444cc6e5e08d9bc8a076b%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637748123273843401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=szg5z6exawQXe4V80dsQHVZg2vp1tKmUDoacNbpfqAA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmasjhd%40bath.ac.uk%7Cd9d288b4e6d444cc6e5e08d9bc8a076b%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637748123273843401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pD9K3b3STf%2F4JgT%2BaF5%2FltKJiu%2BCWDawChiIDhVzw0I%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmasjhd%40bath.ac.uk%7Cd9d288b4e6d444cc6e5e08d9bc8a076b%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637748123273853444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZAJR%2F%2B4NLfC%2FrI8TmNNYPQHzxG1m11jZND2xRhn1w4k%3D&reserved=0>.

**Comment by davidcarlisle** [comment]
I'll fix it, thanks for the report
